
GET http://127.0.0.1:3000/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmVVc3VhcmlvIjoiZmVybmFuZG8iLCJpZCI6MiwiaWF0IjoxNzc3NjYyODM1LCJleHAiOjE3Nzc3NTI4MzV9.xGY3dfta87zRvzlf_IgdeoKnIRv056_71fakoA47bsI