
GET http://127.0.0.1:3000/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmVVc3VhcmlvIjoicHJ1ZWJhIiwiaWQiOiJmYzhkNmVmZC1iMmIyLTQ3YjctYWE2NS1mMDhkYjZmOGE0ODYiLCJpYXQiOjE3Nzc4MjA1MzgsImV4cCI6MTc3NzkxMDUzOH0.k0IEm6u-MyDLmJM3IzqjkE3UV72w49T52QPlMld-zLQ